services:
  postgres-primary:
    build:
      context: ./pg_crdt
      dockerfile: dockerfiles/db/Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
      - 5432:5432
    healthcheck:
      test: 'pg_isready -U postgres --dbname=postgres'
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./conf/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./conf/init.sql:/docker-entrypoint-initdb.d/init.sql
  postgres-replica:
    build:
      context: ./pg_crdt
      dockerfile: dockerfiles/db/Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
      - 5433:5432
    healthcheck:
      test: 'pg_isready -U postgres --dbname=postgres'
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./conf/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./conf/init.sql:/docker-entrypoint-initdb.d/init.sql
